# CVS MERGE

In [29]:
#importing
import pandas as pd
import numpy as np
import re

In [30]:
# calling csv files
df = pd.read_csv("../project2/data/games_clean.csv", encoding= "unicode_escape")
df1 = pd.read_csv("../project2/data/elo_diff_win_percentage.csv", encoding= "unicode_escape")

In [31]:
df

,turns,victory_status,winner,white_rating,black_rating,opening_eco,opening_ply,kings_castle,opening,rating_diff,expected_winner
0,13,outoftime,white,1500,1191,D10,5,No,Slav Defense,309,white
1,16,resign,black,1322,1261,B00,4,No,Nimzowitsch Defense,61,white
2,61,mate,white,1496,1500,C20,3,No,King's Pawn Game,-4,black
3,61,mate,white,1439,1454,D02,3,Yes,Queen's Pawn Game,-15,black
4,95,mate,white,1523,1469,C41,5,Yes,Philidor Defense,54,white
...,...,...,...,...,...,...,...,...,...,...,...
20053,24,resign,white,1691,1220,A80,2,Yes,Dutch Defense,471,white
20054,82,mate,black,1233,1196,A41,2,Yes,Queen's Pawn,37,white
20055,35,mate,white,1219,1286,D00,3,Yes,Queen's Pawn Game,-67,black
20056,109,resign,white,1360,1227,B07,4,No,Pirc Defense,133,white
20057,78,mate,black,1235,1339,D00,3,Yes,Queen's Pawn Game,-104,black

In [32]:
df1

    elo_diff  win_percentage
0        800            0.99
1        750            1.32
2        700            1.75
3        650            2.32
4        600            3.07
5        550            4.05
6        500            5.32
7        450            6.98
8        400            9.09
9        350           11.77
10       300           15.10
11       250           19.17
12       200           24.03
13       150           29.66
14       100           35.99
15        50           42.85
16         0           50.00
17       -50           57.15
18      -100           64.01
19      -150           70.34
20      -200           75.97
21      -250           80.83
22      -300           84.90
23      -350           88.23
24      -400           90.91
25      -450           93.02
26      -500           94.68
27      -550           95.95
28      -600           96.93
29      -650           97.68
30      -700           98.25
31      -750           98.68
32      -800           99.01

In [33]:
#function for closer value on elo range table
def find_nearest(array, value):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return array[idx]

In [34]:
array = df1["elo_diff"]

In [35]:
#making new columns with the value of elo difference
elo_diff = []
for i in df["rating_diff"]:
    x = find_nearest(array, value=i)
    elo_diff.append(x)

In [36]:
# making the new column
df["elo_diff"] = elo_diff

In [37]:
df

,turns,victory_status,winner,white_rating,black_rating,opening_eco,opening_ply,kings_castle,opening,rating_diff,expected_winner,elo_diff
0,13,outoftime,white,1500,1191,D10,5,No,Slav Defense,309,white,300
1,16,resign,black,1322,1261,B00,4,No,Nimzowitsch Defense,61,white,50
2,61,mate,white,1496,1500,C20,3,No,King's Pawn Game,-4,black,0
3,61,mate,white,1439,1454,D02,3,Yes,Queen's Pawn Game,-15,black,0
4,95,mate,white,1523,1469,C41,5,Yes,Philidor Defense,54,white,50
...,...,...,...,...,...,...,...,...,...,...,...,...
20053,24,resign,white,1691,1220,A80,2,Yes,Dutch Defense,471,white,450
20054,82,mate,black,1233,1196,A41,2,Yes,Queen's Pawn,37,white,50
20055,35,mate,white,1219,1286,D00,3,Yes,Queen's Pawn Game,-67,black,-50
20056,109,resign,white,1360,1227,B07,4,No,Pirc Defense,133,white,150
20057,78,mate,black,1235,1339,D00,3,Yes,Queen's Pawn Game,-104,black,-100

In [38]:
# funtion to extract array of the len of the data frame with the win percentage
win_percentage = []
for i in df["elo_diff"]:
    x = df1.loc[(df1["elo_diff"] == i)]
    for i in x.win_percentage:
        z = i
        win_percentage.append(z)

In [39]:
#adding the new column based on the array extracted before
df["expected_win_percentage"] = win_percentage

In [40]:
df

,turns,victory_status,winner,white_rating,black_rating,opening_eco,opening_ply,kings_castle,opening,rating_diff,expected_winner,elo_diff,expected_win_percentage
0,13,outoftime,white,1500,1191,D10,5,No,Slav Defense,309,white,300,15.10
1,16,resign,black,1322,1261,B00,4,No,Nimzowitsch Defense,61,white,50,42.85
2,61,mate,white,1496,1500,C20,3,No,King's Pawn Game,-4,black,0,50.00
3,61,mate,white,1439,1454,D02,3,Yes,Queen's Pawn Game,-15,black,0,50.00
4,95,mate,white,1523,1469,C41,5,Yes,Philidor Defense,54,white,50,42.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20053,24,resign,white,1691,1220,A80,2,Yes,Dutch Defense,471,white,450,6.98
20054,82,mate,black,1233,1196,A41,2,Yes,Queen's Pawn,37,white,50,42.85
20055,35,mate,white,1219,1286,D00,3,Yes,Queen's Pawn Game,-67,black,-50,57.15
20056,109,resign,white,1360,1227,B07,4,No,Pirc Defense,133,white,150,29.66
20057,78,mate,black,1235,1339,D00,3,Yes,Queen's Pawn Game,-104,black,-100,64.01

In [41]:
#exporting final csv for visualization
df.to_csv("data/final.csv", index = False, encoding='unicode_escape')